# Generated by Django 5.1.4 on 2024-12-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscolasModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("logo", models.URLField()),
            ],
            options={
                "verbose_name": "escola",
                "verbose_name_plural": "escolas",
            },
        ),
        migrations.CreateModel(
            name="ProjetoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "completed"), (1, "incomplete"), (2, "dropped")],
                        default=1,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("conclusion", models.TextField(blank=True, null=True)),
                ("code_ex", models.TextField(blank=True, null=True)),
                ("icon", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TecnologiaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("logo", models.URLField()),
            ],
            options={
                "verbose_name": "tecnologia",
                "verbose_name_plural": "tecnologias",
            },
        ),
        migrations.CreateModel(
            name="CursoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("icon", models.URLField(blank=True, null=True)),
                (
                    "codigo_cert",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "completed"), (1, "incomplete"), (2, "dropped")],
                        default=1,
                    ),
                ),
                ("descricao", models.TextField()),
                ("url", models.URLField()),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.escolasmodel",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.tecnologiamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FooterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.CharField(max_length=100)),
                ("views", models.PositiveIntegerField(default=0)),
                ("author", models.CharField(max_length=255)),
                ("made_in", models.CharField(max_length=255)),
                ("online", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "footer",
                "verbose_name_plural": "footers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id",), name="unique_footer_constraint"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                ("nome_completo", models.CharField(max_length=255)),
                ("nick", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, null=True)),
                ("github", models.URLField()),
                ("linkedin", models.URLField()),
                ("profissao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfis",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id",), name="unique_perfil_constraint"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cursos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_info",
                        to="portfolio.cursomodel",
                    ),
                ),
                (
                    "footer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_info",
                        to="portfolio.footermodel",
                    ),
                ),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_info",
                        to="portfolio.perfilmodel",
                    ),
                ),
                (
                    "projetos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_info",
                        to="portfolio.projetomodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "informação do site",
                "verbose_name_plural": "informações do site",
            },
        ),
        migrations.CreateModel(
            name="SubProjetoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("conclusion", models.TextField(blank=True, null=True)),
                ("code_ex", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "completed"), (1, "incomplete"), (2, "dropped")],
                        default=1,
                    ),
                ),
                ("icon", models.URLField(blank=True, null=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprojetos",
                        to="portfolio.projetomodel",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.tecnologiamodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projetomodel",
            name="tecnologia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.tecnologiamodel",
            ),
        ),
    ]
